#launch.save - право на сохранение мира

servers: #array ports
  8881: L-1 #port - servername in bungeecord
  8882: L-2
  8883: L-3
  8884: L-4
  8885: L-5
  8886: L-6
  8887: L-7
  8888: L-8
  8889: L-9
  8890: L-10
grpc:
  host: 192.168.88.62
  port: 9000
main:
  title: "Главное меню - Launch+"
  nextPage: "Далее"
  prevPage: "Назад"
  server:
    title: "Сервер {name}"
    lore:
      - "Порт: {port}"
      - "Версия: {version}"
      - "Статус: {status}"
      - "Количество игроков: {players}/{maxPlayers}"
create:
  title: "Создание сервера"
settings:
  title: "Настройка своего сервера"
  stopServer:
    name: "Остановить сервер"
    lore:
      - "Остановить сервер"
  deleteWorld:
    name:  "Удалить мир"
    lore:
      - "Delete world"
server:
  create:
    success: "§aИдет создание сервера подождите минуту"
messages:
  world_removed: "§aМир удален"
  server_stopped: "§aСервер остановлен"
  server_created: "§aСервер запускается..."
  not_free_port: "§cНет свободных портов"
  server_not_created: "§cСервер не создан"
  help:
    - "/launch menu - открыть главное меню"
    - "/launch settings - открыть меню сервера"