name: LaunchMenu
version: '${version}'
main: eu.suro.lmenu.LaunchMenu
api-version: 1.15
authors: [ Suro ]
description: This is plugin cleint for grpc server, plugin is create server and check save world or no
